DeviceIDToName = {
  '050' : 'Office Ceiling',
  '053' : 'Office Closet',
  '051' : 'Sara Ceiling',
  '052' : 'Sara Closet',
  '054' : 'Upstairs Hallway',
  '04A' : 'Kate Ceiling',
  '049' : 'Kate Closet',
  '04F' : 'Upstairs Bath',
  '04B' : 'Master Ceiling',
  '04C' : 'Master Closet', 
  '04D' : 'Master Bath',
  '057' : 'Kitchen Ceiling',
  '055' : 'Kitchen Table',
  '062' : 'Foyer',
  '05A' : 'Living Room',
  '054' : 'Upstairs Hallway',
  '056' : 'Downstairs Bath',
  '058' : 'Den Ceiling',
  '059' : 'Downstairs Hall',
  '05D' : 'Laundry Room',
  '05E' : 'Den Closet',
  '05C' : 'Garage Inside',
  '05F' : 'Basement',
  '061' : 'Front Porch',
  '05B' : 'Garage Front',
}
